# Change these first
owner: traktuner # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Authentik
    url: https://id.$DOMAIN2
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/authentik.svg
  - name: UrBackup
    check: "tcp-ping"
    url: backup.$DOMAIN2
    port: 55415
    icon: https://cdn2.steamgriddb.com/icon/52aee03d2e0f909e4311bea5510543c5/32/256x256.png
  - name: Portainer
    url: https://prt-prod.$DOMAIN1
    icon: https://developer.asustor.com/uploadIcons/0020_999_1639454569_Portainer_ce_256.png
  - name: Immich
    url: https://photos.$DOMAIN2
    icon: https://immich.app/img/immich-logo.svg.svg.png
  - name: OpenCloud
    url: https://$DOMAIN2/status.php
    icon: https://opencloud.eu/sites/default/files/media/documents/2025-01/OpenCloud_logo_rgb_digital_petrol_ohne_Schutzraum.svg
  - name: Pferde-helfen-Menschen
    url: https://$DOMAIN3
    icon: https://pferde-helfen-menschen.at/img/wave.png
  - name: Baumschule Frank
    url: https://$DOMAIN5
    icon: https://baumschule-frank.com/wp-content/uploads/2021/02/Kopf_Frank_Website_Header.png
  - name: Urlaub am Jauerling
    url: https://urlaub.amjauerling.at
    icon: https://urlaub.amjauerling.at/wp-content/uploads/sites/3/2025/09/amjauerling.png

assignees: # Users to assign downtime issues (optional)
  - traktuner

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.oncloud.at
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night
  name: Service Status
  introTitle: "Service Status Summary"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
