# Change these first
owner: traktuner # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Anakin
    url: https://anakin.langstadlinger.eu
  - name: VMM
    url: https://vmm.langstadlinger.eu
  - name: ABB Restore
    url: https://backup.langstadlinger.eu
  - name: Portainer
    url: https://prt-prod.langstadlinger.eu
  - name: Matrix Chat WebUI
    url: https://chat.langstadlinger.eu
  - name: Matrix Chat Synapse Status
    url: https://synapse.langstadlinger.eu
  - name: Matrix Chat API
    url: https://matrix.langstadlinger.eu/googlechat/login/
  - name: Bitwarden
    url: https://pw.langstadlinger.eu
  - name: Zabbix
    url: https://zbx.langstadlinger.eu
  - name: Optoingen-Web
    url: https://optoingen.com
  - name: Baumschule Frank
    url: https://baumschule-frank.com

assignees: # Users to assign downtime issues (optional)
  - traktuner

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.langstadlinger.eu
  #baseUrl: /status
  theme: night
  css: "#sapper > main > section.live-status > article:nth-child(n+1):nth-child(-n+10) { margin-left: 40px; }"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  introTitle: "Service Status Summary"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
