# Change these first
owner: traktuner # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Anakin
    url: https://anakin.$DOMAIN1
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: VMM
    url: https://vmm.$DOMAIN1
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: ABB Backup
    check: "tcp-ping"
    url: backup.$DOMAIN1
    port: 5510
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: ABB Restore
    url: https://backup.$DOMAIN1
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: Portainer
    url: https://prt-prod.$DOMAIN1
    icon: https://developer.asustor.com/uploadIcons/0020_999_1639454569_Portainer_ce_256.png
  - name: Matrix Chat WebUI
    url: https://chat.$DOMAIN2
    icon: https://avatars.githubusercontent.com/u/8418310
  - name: Matrix Chat Synapse Status
    url: https://matrix.$DOMAIN2
    icon: https://avatars.githubusercontent.com/u/8418310
  - name: Matrix Federation Tester
    url: https://federationtester.matrix.org/#$DOMAIN2
    __dangerous__body_down: "Connection Errors"
    icon: https://avatars.githubusercontent.com/u/8418310
  - name: Bitwarden
    url: https://pw.$DOMAIN1
    icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/128x128.png
  - name: Mastodon
    url: https://social.$DOMAIN2
    icon: https://upload.wikimedia.org/wikipedia/commons/4/48/Mastodon_Logotype_%28Simple%29.svg
  - name: Drive
    url: https://drive.$DOMAIN2
    icon: https://www.synology.com/img/dsm/drive/icon_drive@2x.png
  - name: Nextcloud
    url: https://storage.$DOMAIN2
    icon: https://nextcloud.com/wp-content/uploads/2022/11/logo_nextcloud_blue.svg
  - name: Optoingen-Web
    url: https://$DOMAIN4
    icon: https://media.licdn.com/dms/image/C4E0BAQHcoUmHeiJ18g/company-logo_100_100/0/1633736192649?e=1687996800&v=beta&t=Qni0JDFrs4OPojxlkuw7ph-NYVrF_oL0JRxSZ6fIIAg
  - name: Pferde-helfen-Menschen
    url: https://$DOMAIN3
    icon: https://pferde-helfen-menschen.at/img/wave.png
  - name: Luke
    url: https://langstadlingerbak.de4.quickconnect.to
    __dangerous__body_down: "Cannot connect to"
    icon: https://www.synology.com/img/company/branding/synology_logo_variations2-4.jpg
  - name: Baumschule Frank
    url: https://$DOMAIN5
    icon: https://baumschule-frank.com/wp-content/uploads/2021/02/Kopf_Frank_Website_Header.png

assignees: # Users to assign downtime issues (optional)
  - traktuner

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.oncloud.at
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night
  name: Service Status
  introTitle: "Service Status Summary"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
